# Generated by Django 4.1.2 on 2022-10-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.PositiveIntegerField(unique=True, verbose_name="User ID in Telegram"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name of a user")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="O",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Telegram Username"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date created"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date updated")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
